"""add_img_link_hotel_table

Revision ID: 0c38ca9b4cb4
Revises: 2fe7e7802026
Create Date: 2025-05-13 12:31:20.945159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c38ca9b4cb4'
down_revision = '2fe7e7802026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_data', schema=None) as batch_op:
        batch_op.drop_column('img_link')

    # ### end Alembic commands ###
