"""update_city_name_column_constraint

Revision ID: 19c5993bea7b
Revises: f7702f288662
Create Date: 2025-05-22 15:39:02.998505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c5993bea7b'
down_revision = 'f7702f288662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_data', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_data_city_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('hotel_data_city_name_key', ['city_name'])

    # ### end Alembic commands ###
