"""update_column_availability

Revision ID: f7702f288662
Revises: d78e811402fb
Create Date: 2025-05-16 10:02:39.796261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7702f288662'
down_revision = 'd78e811402fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('avaialbility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avaialbility', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('availability')

    # ### end Alembic commands ###
